# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

bioc_required: true
use_bioc: true

before_install:
  - wget -O antsr_travis.sh http://bit.ly/antsr_travis_sh
  - cat antsr_travis.sh
  - source ./antsr_travis.sh
  - rm antsr_travis.sh
  - cat DESCRIPTION